// ============================================================
// Handout Generator — Structured PDF handout for tutoring sessions
// ============================================================
// Task 45 (Milestone 2, Feature 3)
//
// Generates a downloadable A4 PDF handout using `pdf-lib` (NOT the
// browser print dialog). The handout includes:
//   1. Header — tutor/agency, student, date, subject, lesson title
//   2. Today's Widgets — list of widget names (from WIDGET_KIND_LABELS)
//      plus an optional canvas screenshot
//   3. "What I Learned Today" — 4 reflection prompts with blank lines
//   4. "Practice Problems" — 3 numbered blank problem spaces
//   5. Footer — page number + "Generated by Superboard" + date
//
// The function returns a `Blob` so it can be wired into a download
// helper (create <a>, click, revoke URL).
// ============================================================

'use client'

import {
  PDFDocument,
  StandardFonts,
  PDFFont,
  PDFPage,
  rgb,
  PDFImage,
} from 'pdf-lib'

// ---- Brand palette (matches the rest of the app) ----
const EMERALD = rgb(0.02, 0.59, 0.41) // #059669
const SLATE_BODY = rgb(0.278, 0.333, 0.412) // #475569
const SLATE_MUTED = rgb(0.45, 0.5, 0.55) // body sub-text
const LINE_GRAY = rgb(0.78, 0.8, 0.82) // blank-line strokes
const DIVIDER_GRAY = rgb(0.9, 0.91, 0.93) // hairline separators

// ---- Page geometry (A4) ----
const PAGE_WIDTH = 595
const PAGE_HEIGHT = 842
const MARGIN_X = 50
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_X * 2 // 495pt
const LINE_HEIGHT = 16
const BOTTOM_LIMIT = MARGIN_X + 36 // never draw below this y

export interface HandoutOptions {
  /** Tutor or agency name shown in the header. Defaults to "Superboard". */
  tutorName?: string
  /** Optional student name shown in the header. */
  studentName?: string
  /** Optional subject shown in the header. */
  subject?: string
  /** Optional lesson title shown in the header. Falls back to "Session Handout". */
  lessonTitle?: string
  /** Human-readable widget names (from WIDGET_KIND_LABELS) currently on the canvas. */
  widgetNames: string[]
  /** Optional PNG screenshot of the canvas (already-encoded bytes). */
  canvasImageBytes?: Uint8Array
}

/**
 * Layout context — a mutable cursor pointing at the "current" page and
 * the y position of the next draw. Section helpers receive this and
 * call `ensureSpace()` before drawing each block; if there isn't enough
 * vertical room left, a new A4 page is appended and the cursor resets.
 */
interface LayoutCtx {
  pdfDoc: PDFDocument
  page: PDFPage
  y: number
  font: PDFFont
  boldFont: PDFFont
  italicFont: PDFFont
}

/**
 * Generate a structured handout PDF as a Blob.
 */
export async function generateHandout(options: HandoutOptions): Promise<Blob> {
  const pdfDoc = await PDFDocument.create()
  pdfDoc.setProducer('Superboard')
  pdfDoc.setCreator('Superboard Handout Generator')
  pdfDoc.setTitle(options.lessonTitle || 'Session Handout')

  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const italicFont = await pdfDoc.embedFont(StandardFonts.HelveticaOblique)

  // Optional canvas screenshot (PNG bytes → PDFImage)
  let canvasImage: PDFImage | undefined
  if (options.canvasImageBytes && options.canvasImageBytes.byteLength > 0) {
    try {
      canvasImage = await pdfDoc.embedPng(options.canvasImageBytes)
    } catch {
      // Not a valid PNG — silently ignore and fall back to text-only widgets section.
      canvasImage = undefined
    }
  }

  const ctx: LayoutCtx = {
    pdfDoc,
    page: pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]),
    y: PAGE_HEIGHT - MARGIN_X,
    font,
    boldFont,
    italicFont,
  }

  // ---- Header block ----
  drawHeader(ctx, options)
  drawDivider(ctx, 8)
  ctx.y -= 16

  // ---- Today's Widgets ----
  drawSectionTitle(ctx, "Today's Widgets")
  ctx.y -= 4
  drawWidgetsSection(ctx, options.widgetNames, canvasImage)
  ctx.y -= 8

  drawDivider(ctx, 4)
  ctx.y -= 16

  // ---- What I Learned Today ----
  drawSectionTitle(ctx, 'What I Learned Today')
  ctx.y -= 4
  drawReflectionSection(ctx)
  ctx.y -= 8

  drawDivider(ctx, 4)
  ctx.y -= 16

  // ---- Practice Problems ----
  drawSectionTitle(ctx, 'Practice Problems')
  ctx.y -= 4
  drawPracticeSection(ctx)

  // ---- Footer on every page ----
  const pageCount = pdfDoc.getPageCount()
  for (let i = 0; i < pageCount; i++) {
    drawFooter(pdfDoc.getPage(i), i + 1, pageCount, font)
  }

  const pdfBytes = await pdfDoc.save()
  // `pdfBytes` is a Uint8Array; wrap in a fresh Uint8Array so the Blob
  // constructor is happy across TS lib targets.
  return new Blob([new Uint8Array(pdfBytes)], { type: 'application/pdf' })
}

// ============================================================
// Layout helpers
// ============================================================

/**
 * Ensure at least `needed` points of vertical space remain on the
 * current page; otherwise append a new A4 page and reset the cursor.
 * Always mutates `ctx` to reflect the (possibly new) current page / y.
 */
function ensureSpace(ctx: LayoutCtx, needed: number): void {
  if (ctx.y - needed < BOTTOM_LIMIT) {
    ctx.page = ctx.pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
    ctx.y = PAGE_HEIGHT - MARGIN_X
  }
}

/** Draw a hairline horizontal divider at `ctx.y - offset`. */
function drawDivider(ctx: LayoutCtx, offset: number): void {
  ctx.page.drawLine({
    start: { x: MARGIN_X, y: ctx.y - offset },
    end: { x: PAGE_WIDTH - MARGIN_X, y: ctx.y - offset },
    thickness: 0.75,
    color: DIVIDER_GRAY,
  })
}

/** Draw a section title (emerald, bold) with a thin emerald underline. */
function drawSectionTitle(ctx: LayoutCtx, title: string): void {
  ensureSpace(ctx, 28)
  ctx.page.drawText(title, {
    x: MARGIN_X,
    y: ctx.y - 12,
    size: 13,
    font: ctx.boldFont,
    color: EMERALD,
  })
  const titleWidth = ctx.boldFont.widthOfTextAtSize(title, 13)
  ctx.page.drawLine({
    start: { x: MARGIN_X, y: ctx.y - 16 },
    end: { x: MARGIN_X + titleWidth, y: ctx.y - 16 },
    thickness: 1.25,
    color: EMERALD,
  })
  ctx.y -= 24
}

/** Draw a blank fill-in line from x1 to x2 at the given y. */
function drawBlankLine(page: PDFPage, x1: number, y: number, x2: number): void {
  page.drawLine({
    start: { x: x1, y },
    end: { x: x2, y },
    thickness: 0.6,
    color: LINE_GRAY,
  })
}

/** Naïve word-wrap for a single line of text. */
function wrapText(text: string, maxWidth: number, font: PDFFont, size: number): string[] {
  if (!text) return ['']
  const words = text.split(/\s+/)
  const lines: string[] = []
  let cur = ''
  for (const w of words) {
    const candidate = cur ? `${cur} ${w}` : w
    if (font.widthOfTextAtSize(candidate, size) > maxWidth) {
      if (cur) {
        lines.push(cur)
        cur = w
      } else {
        // Single word longer than the available width — push as-is.
        lines.push(w)
        cur = ''
      }
    } else {
      cur = candidate
    }
  }
  if (cur) lines.push(cur)
  return lines.length > 0 ? lines : ['']
}

// ============================================================
// Section renderers
// ============================================================

function drawHeader(ctx: LayoutCtx, options: HandoutOptions): void {
  const tutorName = options.tutorName || 'Superboard'
  const lessonTitle = options.lessonTitle || 'Session Handout'
  const dateStr = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  // Tutor/Agency name (large, emerald, bold) — top-left
  ctx.page.drawText(tutorName, {
    x: MARGIN_X,
    y: ctx.y - 14,
    size: 18,
    font: ctx.boldFont,
    color: EMERALD,
  })

  // Lesson title — top-right, same baseline
  const titleWidth = ctx.boldFont.widthOfTextAtSize(lessonTitle, 13)
  ctx.page.drawText(lessonTitle, {
    x: PAGE_WIDTH - MARGIN_X - titleWidth,
    y: ctx.y - 12,
    size: 13,
    font: ctx.boldFont,
    color: SLATE_BODY,
  })

  ctx.y -= 24

  // Meta line: "Student: ___    |    Date: ___"
  const studentPart = options.studentName ? `Student: ${options.studentName}` : ''
  const datePart = `Date: ${dateStr}`
  const metaLine = [studentPart, datePart].filter(Boolean).join('    |    ')
  ctx.page.drawText(metaLine, {
    x: MARGIN_X,
    y: ctx.y - 10,
    size: 10,
    font: ctx.font,
    color: SLATE_MUTED,
  })

  // Subject — right-aligned on the same baseline
  if (options.subject) {
    const subjectText = `Subject: ${options.subject}`
    const subjWidth = ctx.font.widthOfTextAtSize(subjectText, 10)
    ctx.page.drawText(subjectText, {
      x: PAGE_WIDTH - MARGIN_X - subjWidth,
      y: ctx.y - 10,
      size: 10,
      font: ctx.font,
      color: SLATE_MUTED,
    })
  }

  ctx.y -= 18
}

function drawWidgetsSection(
  ctx: LayoutCtx,
  widgetNames: string[],
  canvasImage?: PDFImage,
): void {
  if (widgetNames.length === 0) {
    // Empty state — italic note
    const note = 'No widgets used in this session.'
    const lines = wrapText(note, CONTENT_WIDTH, ctx.italicFont, 11)
    for (const line of lines) {
      ensureSpace(ctx, LINE_HEIGHT)
      ctx.page.drawText(line, {
        x: MARGIN_X,
        y: ctx.y - 11,
        size: 11,
        font: ctx.italicFont,
        color: SLATE_MUTED,
      })
      ctx.y -= LINE_HEIGHT
    }
    return
  }

  // Bulleted list of widget names
  for (const name of widgetNames) {
    ensureSpace(ctx, LINE_HEIGHT)
    // Bullet glyph
    ctx.page.drawText('•', {
      x: MARGIN_X,
      y: ctx.y - 11,
      size: 11,
      font: ctx.font,
      color: EMERALD,
    })
    // Wrap long names
    const maxNameWidth = CONTENT_WIDTH - 18
    const nameLines = wrapText(name, maxNameWidth, ctx.font, 11)
    nameLines.forEach((line, idx) => {
      if (idx > 0) ensureSpace(ctx, LINE_HEIGHT)
      ctx.page.drawText(line, {
        x: MARGIN_X + 14,
        y: ctx.y - 11,
        size: 11,
        font: ctx.font,
        color: SLATE_BODY,
      })
      if (idx < nameLines.length - 1) ctx.y -= LINE_HEIGHT
    })
    ctx.y -= LINE_HEIGHT + 2
  }

  // Optional canvas screenshot
  if (canvasImage) {
    ctx.y -= 6
    ensureSpace(ctx, LINE_HEIGHT + 6)
    ctx.page.drawText('Canvas snapshot:', {
      x: MARGIN_X,
      y: ctx.y - 11,
      size: 10,
      font: ctx.italicFont,
      color: SLATE_MUTED,
    })
    ctx.y -= LINE_HEIGHT + 4

    // Fit image within content width, preserve aspect ratio, cap height at 220pt
    let finalW = Math.min(CONTENT_WIDTH, canvasImage.width)
    let finalH = (canvasImage.height / canvasImage.width) * finalW
    const maxImgH = 220
    if (finalH > maxImgH) {
      finalH = maxImgH
      finalW = (canvasImage.width / canvasImage.height) * maxImgH
    }
    const imgX = MARGIN_X + (CONTENT_WIDTH - finalW) / 2

    ensureSpace(ctx, finalH + 8)
    ctx.page.drawImage(canvasImage, {
      x: imgX,
      y: ctx.y - finalH,
      width: finalW,
      height: finalH,
    })
    ctx.y -= finalH + 6
  }
}

function drawReflectionSection(ctx: LayoutCtx): void {
  const prompts = [
    'Today I learned about:',
    'The most important thing was:',
    'I still need help with:',
    'One thing I will practice:',
  ]

  for (const prompt of prompts) {
    ensureSpace(ctx, LINE_HEIGHT + 8)
    ctx.page.drawText(prompt, {
      x: MARGIN_X,
      y: ctx.y - 11,
      size: 11,
      font: ctx.font,
      color: SLATE_BODY,
    })
    const promptWidth = ctx.font.widthOfTextAtSize(prompt, 11)
    drawBlankLine(ctx.page, MARGIN_X + promptWidth + 6, ctx.y - 9, PAGE_WIDTH - MARGIN_X)
    ctx.y -= LINE_HEIGHT + 4
  }
}

function drawPracticeSection(ctx: LayoutCtx): void {
  for (let i = 1; i <= 3; i++) {
    ensureSpace(ctx, LINE_HEIGHT)
    const numText = `${i}.`
    ctx.page.drawText(numText, {
      x: MARGIN_X,
      y: ctx.y - 11,
      size: 11,
      font: ctx.font,
      color: EMERALD,
    })
    const numWidth = ctx.font.widthOfTextAtSize(numText, 11)
    drawBlankLine(ctx.page, MARGIN_X + numWidth + 8, ctx.y - 9, PAGE_WIDTH - MARGIN_X)
    ctx.y -= LINE_HEIGHT + 2

    // Two more full-width blank lines per problem
    for (let j = 0; j < 2; j++) {
      ensureSpace(ctx, LINE_HEIGHT)
      drawBlankLine(ctx.page, MARGIN_X + 16, ctx.y - 9, PAGE_WIDTH - MARGIN_X)
      ctx.y -= LINE_HEIGHT + 2
    }
    ctx.y -= 6
  }
}

function drawFooter(
  page: PDFPage,
  pageNum: number,
  pageCount: number,
  font: PDFFont,
): void {
  const footerY = 28
  const dateStr = new Date().toLocaleDateString()

  // Left — "Generated by Superboard"
  page.drawText('Generated by Superboard', {
    x: MARGIN_X,
    y: footerY,
    size: 9,
    font,
    color: SLATE_MUTED,
  })

  // Center — date
  const dateText = dateStr
  const dateWidth = font.widthOfTextAtSize(dateText, 9)
  page.drawText(dateText, {
    x: (PAGE_WIDTH - dateWidth) / 2,
    y: footerY,
    size: 9,
    font,
    color: SLATE_MUTED,
  })

  // Right — "Page X of Y"
  const pageText = `Page ${pageNum} of ${pageCount}`
  const pageWidth = font.widthOfTextAtSize(pageText, 9)
  page.drawText(pageText, {
    x: PAGE_WIDTH - MARGIN_X - pageWidth,
    y: footerY,
    size: 9,
    font,
    color: SLATE_MUTED,
  })

  // Hairline above the footer
  page.drawLine({
    start: { x: MARGIN_X, y: footerY + 12 },
    end: { x: PAGE_WIDTH - MARGIN_X, y: footerY + 12 },
    thickness: 0.5,
    color: DIVIDER_GRAY,
  })
}

/**
 * Trigger a browser download for the generated handout Blob.
 *
 * Usage:
 *   const blob = await generateHandout({ ... })
 *   downloadHandoutBlob(blob, 'superboard-handout.pdf')
 */
export function downloadHandoutBlob(blob: Blob, filename = 'superboard-handout.pdf'): void {
  if (typeof document === 'undefined') return
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  // Defer revoke so the download has time to start in all browsers.
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
