import json

all_ex = []
counters = {}

def ex(rule, diff, q, opts, ci, expls):
    if rule not in counters: counters[rule] = 0
    counters[rule] += 1
    bands_map = {'beginner': 'K-5', 'intermediate': '6-8', 'advanced': '9-12'}
    band = bands_map[diff]
    num = str(counters[rule]).zfill(3)
    all_ex.append({'id': 'p-'+rule+'-'+num, 'rule': rule, 'difficulty': diff, 'band': band, 'question': q, 'options': opts, 'correctIndex': ci, 'explanations': expls})

# ============================================================
# SEMICOLON - 51
# ============================================================
for i in range(17):
    d = 'beginner'
    b = 'K-5'
    n = str(i+1).zfill(3)
    pairs = [
        ('I like dogs; she likes cats.','I like dogs, she likes cats.','I like dogs she likes cats.','Correct. Semicolon joins two independent clauses.','Comma splice - two independent clauses need stronger punctuation.','Run-on sentence with no punctuation.'),
        ('The sky is blue; the sun is bright.','The sky is blue, the sun is bright,','The sky is blue the sun is bright.','Correct. Semicolon joins two related independent clauses.','A comma creates a comma splice; the trailing comma is also wrong.','Run-on sentence.'),
        ('He was tired; he went to bed early.','He was tired, he went to bed early.','He was tired he went to bed early.','Correct. Two independent clauses joined by semicolon.','Comma splice.','Run-on sentence.'),
        ('Rain fell; the streets flooded.','Rain fell, the streets flooded.','Rain fell the streets flooded.','Correct. Two related independent clauses joined by semicolon.','Comma splice.','Run-on.'),
        ('She sings; he dances.','She sings, he dances.','She sings he dances.','Correct. Semicolon joins two independent clauses.','Comma splice.','Run-on.'),
        ('The movie was long; it was also boring.','The movie was long, it was also boring.','The movie was long it was also boring.','Correct. Semicolon properly joins two clauses.','Comma splice.','Run-on.'),
        ('We can go to the beach; we can stay home.','We can go to the beach, we can stay home.','We can go to the beach; or we can stay home.','Correct. Two independent clauses joined by semicolon.','Comma splice.','A semicolon should not be followed by a coordinating conjunction like or.'),
        ('Birds fly; fish swim.','Birds fly, fish swim.','Birds fly fish swim.','Correct. Semicolon joins two contrasting clauses.','Comma splice.','Run-on.'),
        ('The test was hard; I did my best.','The test was hard, I did my best.','The test was hard I did my best.','Correct. Semicolon joins two independent clauses.','Comma splice.','Run-on.'),
        ('I woke up late; I missed the bus.','I woke up late, I missed the bus.','I woke up late I missed the bus.','Correct. Semicolon separates two independent clauses.','Comma splice.','Run-on.'),
        ('She studied hard; therefore, she got an A.','She studied hard, therefore, she got an A.','She studied hard; therefore she got an A.','Correct. Semicolon before and comma after the conjunctive adverb.','Comma splice before the conjunctive adverb.','A comma should follow the conjunctive adverb.'),
        ('The food was good; the service was terrible.','The food was good, the service was terrible.','The food was good the service was terrible.','Correct. Semicolon joins two contrasting clauses.','Comma splice.','Run-on.'),
        ('He likes hockey; his brother prefers soccer.','He likes hockey, his brother prefers soccer.','He likes hockey his brother prefers soccer.','Correct. Two independent clauses joined by semicolon.','Comma splice.','Run-on.'),
        ('May is warm; June is hotter.','May is warm, June is hotter.','May is warm June is hotter.','Correct. Semicolon joins two related clauses.','Comma splice.','Run-on.'),
        ('Cats are independent; dogs are loyal.','Cats are independent, dogs are loyal.','Cats are independent dogs are loyal.','Correct. Semicolon joins two contrasting clauses.','Comma splice.','Run-on.'),
        ('The game ended; the crowd cheered.','The game ended, the crowd cheered.','The game ended the crowd cheered.','Correct. Semicolon joins two related clauses.','Comma splice.','Run-on.'),
    ]
    if i < len(pairs):
        p = pairs[i]
        ex('semicolon', d, 'Choose the correctly punctuated sentence:', [p[0],p[1],p[2]], 0, [p[3],p[4],p[5]])

# Intermediate semicolons
int_pairs = [
    ('The project was delayed; consequently, the deadline was extended.','The project was delayed, consequently, the deadline was extended.','The project was delayed; consequently the deadline was extended.','Correct. Semicolon before, comma after the conjunctive adverb.','Comma splice before the conjunctive adverb.','Missing comma after the conjunctive adverb.'),
    ('Some students prefer morning classes; others prefer afternoon sessions.','Some students prefer morning classes, others prefer afternoon sessions.','Some students prefer morning classes others prefer afternoon sessions.','Correct. Semicolon joins two independent clauses.','Comma splice.','Run-on.'),
    ('The experiment failed; however, we learned valuable lessons.','The experiment failed, however, we learned valuable lessons.','The experiment failed; however we learned valuable lessons.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after the conjunctive adverb.'),
    ('The team won; furthermore, they broke the record.','The team won, furthermore, they broke the record.','The team won; furthermore they broke the record.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after conjunctive adverb.'),
    ('I have not finished; moreover, I have barely started.','I have not finished, moreover, I have barely started.','I have not finished; moreover I have barely started.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after conjunctive adverb.'),
    ('She did not attend; nonetheless, she submitted her assignment.','She did not attend, nonetheless, she submitted her assignment.','She did not attend; nonetheless she submitted her assignment.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after conjunctive adverb.'),
    ('We visited Paris, France; London, England; and Rome, Italy.','We visited Paris, France, London, England, and Rome, Italy.','We visited Paris France; London England; and Rome Italy.','Correct. Semicolons separate complex list items with internal commas.','Commas alone cannot separate items that already contain internal commas.','Missing commas within the list items.'),
    ('The first place winner received gold; the second place winner received silver.','The first place winner received gold, the second place winner received silver.','The first place winner received gold the second place winner received silver.','Correct. Two independent clauses joined by semicolon.','Comma splice.','Run-on.'),
    ('The recipe requires flour, sugar, and eggs; the frosting needs butter, cream, and vanilla.','The recipe requires flour, sugar, and eggs, the frosting needs butter, cream, and vanilla.','The recipe requires flour, sugar, and eggs the frosting needs butter, cream, and vanilla.','Correct. Semicolon separates clauses that contain commas.','Comma splice.','Run-on.'),
    ('He studied for weeks; as a result, his grades improved.','He studied for weeks, as a result, his grades improved.','He studied for weeks; as a result his grades improved.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after the conjunctive adverb.'),
    ('The museum is closed on Mondays; it is open Tuesday through Sunday.','The museum is closed on Mondays, it is open Tuesday through Sunday.','The museum is closed on Mondays it is open Tuesday through Sunday.','Correct. Two independent clauses joined by semicolon.','Comma splice.','Run-on.'),
    ('The results were inconclusive; similarly, the previous study had mixed findings.','The results were inconclusive, similarly, the previous study had mixed findings.','The results were inconclusive; similarly the previous study had mixed findings.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after conjunctive adverb.'),
    ('The concert was sold out; however, we found tickets online.','The concert was sold out, however, we found tickets online.','The concert was sold out; however we found tickets online.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after conjunctive adverb.'),
    ('I finished my homework; meanwhile, my brother was still playing games.','I finished my homework, meanwhile, my brother was still playing games.','I finished my homework; meanwhile my brother was still playing games.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after conjunctive adverb.'),
    ('She loves the ocean; I prefer the mountains.','She loves the ocean, I prefer the mountains.','She loves the ocean I prefer the mountains.','Correct. Semicolon joins contrasting clauses.','Comma splice.','Run-on.'),
    ('The author revised the manuscript; the editor approved the changes.','The author revised the manuscript, the editor approved the changes.','The author revised the manuscript the editor approved the changes.','Correct. Two independent clauses joined by semicolon.','Comma splice.','Run-on.'),
]
for i, p in enumerate(int_pairs):
    ex('semicolon', 'intermediate', 'Choose the correctly punctuated sentence:', [p[0],p[1],p[2]], 0, [p[3],p[4],p[5]])

# Advanced semicolons
adv_pairs = [
    ('The defendant maintained his innocence; the evidence, however, told a different story.','The defendant maintained his innocence, the evidence, however, told a different story.','The defendant maintained his innocence; the evidence however told a different story.','Correct. Semicolon joins clauses; commas set off conjunctive adverb.','Comma splice before the second clause.','Missing commas around the conjunctive adverb.'),
    ('The data suggests a strong correlation; the researchers, nevertheless, urge caution.','The data suggests a strong correlation, the researchers, nevertheless, urge caution.','The data suggests a strong correlation; the researchers nevertheless urge caution.','Correct. Semicolon joins clauses; commas set off conjunctive adverb.','Comma splice.','Missing commas around the conjunctive adverb.'),
    ('The committee included Dr. Smith, a neurologist; Prof. Jones, a physicist; and Ms. Lee, a biologist.','The committee included Dr. Smith, a neurologist, Prof. Jones, a physicist, and Ms. Lee, a biologist.','The committee included Dr. Smith a neurologist; Prof. Jones a physicist; and Ms. Lee a biologist.','Correct. Semicolons separate complex list items with internal commas.','Commas alone cannot clarify which items belong together.','Missing commas within the list items.'),
    ('AI has transformed medicine; correspondingly, it has raised ethical concerns.','AI has transformed medicine, correspondingly, it has raised ethical concerns.','AI has transformed medicine; correspondingly it has raised ethical concerns.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after the conjunctive adverb.'),
    ('The treaty was ratified by the Senate; moreover, it received bipartisan support.','The treaty was ratified by the Senate, moreover, it received bipartisan support.','The treaty was ratified by the Senate; moreover it received bipartisan support.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after conjunctive adverb.'),
    ('The hypothesis was rejected; the methodology, however, was praised.','The hypothesis was rejected, the methodology, however, was praised.','The hypothesis was rejected; the methodology however was praised.','Correct. Semicolon joins clauses; commas set off conjunctive adverb.','Comma splice.','Missing commas around conjunctive adverb.'),
    ('Inflation has decreased; conversely, consumer confidence has increased.','Inflation has decreased, conversely, consumer confidence has increased.','Inflation has decreased; conversely consumer confidence has increased.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after conjunctive adverb.'),
    ('The author argues that language shapes thought; this idea, known as linguistic relativity, remains controversial.','The author argues that language shapes thought, this idea, known as linguistic relativity, remains controversial.','The author argues that language shapes thought; this idea known as linguistic relativity, remains controversial.','Correct. Semicolon joins independent clauses; appositive set off by commas.','Comma splice before the second clause.','Missing comma before the appositive phrase.'),
    ('The CEO resigned; the stock price, predictably, fell sharply.','The CEO resigned, the stock price, predictably, fell sharply.','The CEO resigned; the stock price predictably, fell sharply.','Correct. Semicolon joins clauses; commas set off conjunctive adverb.','Comma splice.','Misplaced commas around the conjunctive adverb.'),
    ('The pandemic disrupted supply chains; consequently, many businesses faced challenges.','The pandemic disrupted supply chains, consequently, many businesses faced challenges.','The pandemic disrupted supply chains; consequently many businesses faced challenges.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after conjunctive adverb.'),
    ('The first experiment yielded positive results; the second, by contrast, produced null findings.','The first experiment yielded positive results, the second, by contrast, produced null findings.','The first experiment yielded positive results; the second by contrast, produced null findings.','Correct. Semicolon joins clauses; commas set off the contrast phrase.','Comma splice.','Missing comma before the parenthetical phrase.'),
    ('Genetic engineering offers promise; likewise, it presents ethical dilemmas.','Genetic engineering offers promise, likewise, it presents ethical dilemmas.','Genetic engineering offers promise; likewise it presents ethical dilemmas.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after conjunctive adverb.'),
    ('The candidate promised tax cuts; additionally, she advocated for defense spending.','The candidate promised tax cuts, additionally, she advocated for defense spending.','The candidate promised tax cuts; additionally she advocated for defense spending.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after conjunctive adverb.'),
    ('The treaty established new borders; finally, it created a peacekeeping force.','The treaty established new borders, finally, it created a peacekeeping force.','The treaty established new borders; finally it created a peacekeeping force.','Correct. Semicolon before, comma after conjunctive adverb.','Comma splice.','Missing comma after conjunctive adverb.'),
    ('The philosopher argued that knowledge is provisional; this view, paradoxically, is presented as certain.','The philosopher argued that knowledge is provisional, this view, paradoxically, is presented as certain.','The philosopher argued that knowledge is provisional; this view paradoxically, is presented as certain.','Correct. Semicolon joins clauses; commas set off parenthetical adverb.','Comma splice.','Misplaced commas.'),
]
for i, p in enumerate(adv_pairs):
    ex('semicolon', 'advanced', 'Choose the correctly punctuated sentence:', [p[0],p[1],p[2]], 0, [p[3],p[4],p[5]])

print('Semicolon:', counters['semicolon'])

# ============================================================
# COLON - 51
# ============================================================
# Beginner
colon_b = [
    ('Please bring the following items: pencils, paper, and erasers.','Please bring the following items pencils, paper, and erasers.','Please bring the following items; pencils, paper, and erasers.','Correct. A colon introduces a list after the phrase.','Missing colon before the list.','A semicolon does not introduce a list.'),
    ('There are three primary colors: red, blue, and yellow.','There are three primary colors red, blue, and yellow.','There are three primary colors; red, blue, and yellow.','Correct. Colon introduces the list.','Missing colon.','Semicolon does not introduce lists.'),
    ('Dear Mrs. Johnson:','Dear Mrs. Johnson,','Dear Mrs. Johnson;','Correct. A colon follows a formal greeting.','A comma is less formal but acceptable in informal contexts.','A semicolon is never used in a greeting.'),
    ('The answer is simple: practice every day.','The answer is simple practice every day.','The answer is simple; practice every day.','Correct. Colon introduces an explanation.','Missing colon before the explanation.','Semicolon does not introduce explanations.'),
    ('My favorite subjects are math and science.','My favorite subjects are: math and science.','My favorite subjects are; math and science.','Correct. No colon needed when the list follows the verb directly.','No colon is needed after the verb before a short complement.','A semicolon is never used here.'),
    ('The rules are clear: no running, no pushing, and no yelling.','The rules are clear no running, no pushing, and no yelling.','The rules are clear; no running, no pushing, and no yelling.','Correct. Colon introduces the list of rules.','Missing colon.','Semicolon does not introduce lists.'),
    ('She said, \u201cI am happy.\u201d','She said: \u201cI am happy.\u201d','She said; \u201cI am happy.\u201d','Correct. A comma introduces a short quote.','A colon is not used to introduce short dialogue.','A semicolon is never used before a quote.'),
    ('We need three things for the project: markers, poster board, and glue.','We need three things for the project markers, poster board, and glue.','We need three things for the project; markers, poster board, and glue.','Correct. Colon introduces the list.','Missing colon.','Semicolon is wrong here.'),
    ('Remember this rule: always be kind.','Remember this rule always be kind.','Remember this rule; always be kind.','Correct. Colon introduces the emphasized rule.','Missing colon.','Semicolon does not introduce explanations.'),
    ('The store sells fruit: apples, bananas, and oranges.','The store sells fruit apples, bananas, and oranges.','The store sells fruit; apples, bananas, and oranges.','Correct. Colon introduces the list.','Missing colon.','Semicolon is wrong.'),
    ('Time is running out: we need to leave now.','Time is running out we need to leave now.','Time is running out; we need to leave now.','Correct. Colon emphasizes the urgency.','Missing punctuation.','Semicolon could work but the colon adds rhetorical emphasis.'),
    ('I have one goal: to become a doctor.','I have one goal to become a doctor.','I have one goal; to become a doctor.','Correct. Colon introduces the goal/explanation.','Missing colon.','Semicolon does not introduce explanations.'),
    ('The ingredients are flour, sugar, and butter.','The ingredients are: flour, sugar, and butter.','The ingredients are; flour, sugar, and butter.','Correct. No colon needed when the list directly completes the sentence.','No colon needed after the verb before a complement.','A semicolon is never used here.'),
    ('Notice the pattern: each number increases by five.','Notice the pattern each number increases by five.','Notice the pattern; each number increases by five.','Correct. Colon introduces the explanation.','Missing colon.','Semicolon is wrong.'),
    ('Here is the schedule: breakfast at 8, lunch at 12, dinner at 6.','Here is the schedule breakfast at 8, lunch at 12, dinner at 6.','Here is the schedule; breakfast at 8, lunch at 12, dinner at 6.','Correct. Colon introduces the schedule.','Missing colon.','Semicolon is wrong.'),
    ('My dog has one favorite activity: chasing squirrels.','My dog has one favorite activity chasing squirrels.','My dog has one favorite activity; chasing squirrels.','Correct. Colon introduces the emphasized detail.','Missing colon.','Semicolon requires an independent clause.'),
]
for i, p in enumerate(colon_b):
    ex('colon', 'beginner', 'Choose the correctly punctuated sentence:', [p[0],p[1],p[2]], 0, [p[3],p[4],p[5]])

# Intermediate colons
colon_i = [
    ('The scientist made a groundbreaking discovery: a new species of deep-sea fish.','The scientist made a groundbreaking discovery, a new species of deep-sea fish.','The scientist made a groundbreaking discovery; a new species of deep-sea fish.','Correct. Colon introduces the elaboration.','A comma is too weak for this emphasis.','The second part is not an independent clause.'),
    ('The conference will feature three speakers: Dr. Patel, Prof. Chen, and Ms. Rodriguez.','The conference will feature three speakers Dr. Patel, Prof. Chen, and Ms. Rodriguez.','The conference will feature three speakers; Dr. Patel, Prof. Chen, and Ms. Rodriguez.','Correct. Colon introduces the list.','Missing colon.','Semicolon does not introduce lists.'),
    ('The evidence points to one conclusion: the defendant is innocent.','The evidence points to one conclusion, the defendant is innocent.','The evidence points to one conclusion; the defendant is innocent.','Correct. Colon emphasizes the conclusion.','Comma splice with an independent clause.','Semicolon could work but colon adds emphasis.'),
    ('To Whom It May Concern:','To Whom It May Concern,','To Whom It May Concern;','Correct. A colon follows formal salutations.','A comma is informal.','A semicolon is never used in a salutation.'),
    ('The recipe calls for these ingredients: two cups of flour, one cup of sugar, and three eggs.','The recipe calls for these ingredients two cups of flour, one cup of sugar, and three eggs.','The recipe calls for these ingredients; two cups of flour, one cup of sugar, and three eggs.','Correct. Colon after the phrase introducing a list.','Missing colon.','Semicolon is wrong.'),
    ('Shakespeare wrote, \u201cAll the world\u2019s a stage.\u201d','Shakespeare wrote: \u201cAll the world\u2019s a stage.\u201d','Shakespeare wrote; \u201cAll the world\u2019s a stage.\u201d','Correct. A comma introduces a short quotation integrated into the sentence.','A colon is less common for short quotes that flow from the sentence.','A semicolon is never used before a quotation.'),
    ('The students were asked to bring pens, notebooks, and calculators.','The students were asked to bring: pens, notebooks, and calculators.','The students were asked to bring; pens, notebooks, and calculators.','Correct. No colon needed when the list follows the verb directly.','No colon is needed after a verb phrase before a list.','A semicolon is never used here.'),
    ('The principle is straightforward: treat others as you wish to be treated.','The principle is straightforward, treat others as you wish to be treated.','The principle is straightforward; treat others as you wish to be treated.','Correct. Colon introduces the explanation of the principle.','Comma splice.','Semicolon could work but colon adds emphasis.'),
    ('The report includes several sections: introduction, methodology, results, and discussion.','The report includes several sections introduction, methodology, results, and discussion.','The report includes several sections; introduction, methodology, results, and discussion.','Correct. Colon introduces the list of sections.','Missing colon.','Semicolon is wrong.'),
    ('The coach gave one instruction: give it everything you have.','The coach gave one instruction, give it everything you have.','The coach gave one instruction; give it everything you have.','Correct. Colon emphasizes the single instruction.','Comma splice.','Semicolon could work but colon is better.'),
    ('Please note the following: the test has been rescheduled to Friday.','Please note the following the test has been rescheduled to Friday.','Please note the following; the test has been rescheduled to Friday.','Correct. Colon after the introductory phrase.','Missing colon.','Semicolon is wrong.'),
    ('There is one thing I cannot tolerate: dishonesty.','There is one thing I cannot tolerate, dishonesty.','There is one thing I cannot tolerate; dishonesty.','Correct. Colon introduces the emphasis/noun.','Comma splice with an appositive.','Semicolon requires an independent clause.'),
    ('The agenda is as follows: opening remarks, panel discussion, and Q&A.','The agenda is as follows opening remarks, panel discussion, and Q&A.','The agenda is as follows; opening remarks, panel discussion, and Q&A.','Correct. The phrase \u201cas follows\u201d is always followed by a colon.','Missing colon after \u201cas follows\u201d.','Semicolon is wrong.'),
    ('My mother gave me excellent advice: never give up on your dreams.','My mother gave me excellent advice, never give up on your dreams.','My mother gave me excellent advice; never give up on your dreams.','Correct. Colon introduces the advice.','Comma splice.','Semicolon could work but colon adds emphasis.'),
    ('The sign reads: \u201cNo trespassing.\u201d','The sign reads, \u201cNo trespassing.\u201d','The sign reads; \u201cNo trespassing.\u201d','Correct. A colon introduces a formal/complete-sentence quotation.','A comma could work but is less formal.','A semicolon is never used before a quotation.'),
]
for i, p in enumerate(colon_i):
    ex('colon', 'intermediate', 'Choose the correctly punctuated sentence:', [p[0],p[1],p[2]], 0, [p[3],p[4],p[5]])

# Advanced colons
colon_a = [
    ('The research identified a critical flaw: the sample size was insufficient.','The research identified a critical flaw, the sample size was insufficient.','The research identified a critical flaw; the sample size was insufficient.','Correct. Colon emphasizes the explanation.','Comma splice.','Semicolon could work but colon is stronger rhetorically.'),
    ('The Constitution establishes three branches: legislative, executive, and judicial.','The Constitution establishes three branches, legislative, executive, and judicial.','The Constitution establishes three branches; legislative, executive, and judicial.','Correct. Colon introduces the list.','Missing colon.','Semicolon does not introduce lists.'),
    ('Aristotle defined three modes of persuasion: ethos, pathos, and logos.','Aristotle defined three modes of persuasion, ethos, pathos, and logos.','Aristotle defined three modes of persuasion; ethos, pathos, and logos.','Correct. Colon introduces the list.','Missing colon.','Semicolon is wrong.'),
    ('The study revealed a surprising finding: students who studied in short bursts retained more.','The study revealed a surprising finding, students who studied in short bursts retained more.','The study revealed a surprising finding; students who studied in short bursts retained more.','Correct. Colon emphasizes the finding.','Comma splice.','Semicolon could work but colon adds emphasis.'),
    ('The contract stipulated one non-negotiable term: the artist retains all copyright.','The contract stipulated one non-negotiable term, the artist retains all copyright.','The contract stipulated one non-negotiable term; the artist retains all copyright.','Correct. Colon introduces the explanation.','Comma splice.','Semicolon could work but colon adds emphasis.'),
    ('The professor posed a provocative question: \u201cIf free will does not exist, can moral responsibility?\u201d','The professor posed a provocative question, \u201cIf free will does not exist, can moral responsibility?\u201d','The professor posed a provocative question; \u201cIf free will does not exist, can moral responsibility?\u201d','Correct. A colon introduces a formal/complete-sentence quotation.','A comma is less formal for such a significant quotation.','A semicolon is never used before a quotation.'),
    ('The evidence leads to one conclusion: the policy has failed.','The evidence leads to one conclusion, the policy has failed.','The evidence leads to one conclusion; the policy has failed.','Correct. Colon emphasizes the conclusion.','Comma splice.','Semicolon could work but colon is stronger.'),
    ('The declaration was unequivocal: \u201cWe will no longer tolerate injustice.\u201d','The declaration was unequivocal, \u201cWe will no longer tolerate injustice.\u201d','The declaration was unequivocal; \u201cWe will no longer tolerate injustice.\u201d','Correct. Colon introduces a formal quotation.','A comma could work for shorter quotes but colon is preferred.','Semicolon is never used before a quotation.'),
    ('Newton\u2019s third law states: for every action, there is an equal and opposite reaction.','Newton\u2019s third law states, for every action, there is an equal and opposite reaction.','Newton\u2019s third law states; for every action, there is an equal and opposite reaction.','Correct. Colon introduces a formal statement/principle.','A comma is less formal.','Semicolon is wrong here.'),
    ('The historian identified the primary cause: economic inequality exacerbated by drought.','The historian identified the primary cause, economic inequality exacerbated by drought.','The historian identified the primary cause; economic inequality exacerbated by drought.','Correct. Colon introduces the explanation.','Comma splice.','Semicolon could work but colon emphasizes.'),
    ('The CEO outlined the new strategy: focus on sustainability and expand into new markets.','The CEO outlined the new strategy, focus on sustainability and expand into new markets.','The CEO outlined the new strategy; focus on sustainability and expand into new markets.','Correct. Colon introduces the strategy.','Comma splice.','The second part is not an independent clause.'),
    ('Darwin\u2019s theory rests on one fundamental principle: natural selection.','Darwin\u2019s theory rests on one fundamental principle, natural selection.','Darwin\u2019s theory rests on one fundamental principle; natural selection.','Correct. Colon introduces the principle.','A comma could work for a simple appositive but colon is stronger.','Semicolon requires an independent clause.'),
    ('The report concludes with a warning: \u201cFailure to act now will have irreversible consequences.\u201d','The report concludes with a warning, \u201cFailure to act now will have irreversible consequences.\u201d','The report concludes with a warning; \u201cFailure to act now will have irreversible consequences.\u201d','Correct. Colon introduces a formal quotation.','A comma is less formal.','Semicolon is wrong.'),
    ('The treaty established three provisions: territorial boundaries, trade agreements, and defense pacts.','The treaty established three provisions territorial boundaries, trade agreements, and defense pacts.','The treaty established three provisions; territorial boundaries, trade agreements, and defense pacts.','Correct. Colon introduces the list.','Missing colon.','Semicolon does not introduce lists.'),
    ('The experiment proved one thing beyond doubt: light behaves as both a wave and a particle.','The experiment proved one thing beyond doubt, light behaves as both a wave and a particle.','The experiment proved one thing beyond doubt; light behaves as both a wave and a particle.','Correct. Colon introduces the emphasized finding.','Comma splice.','Semicolon could work but colon adds emphasis.'),
]
for i, p in enumerate(colon_a):
    ex('colon', 'advanced', 'Choose the correctly punctuated sentence:', [p[0],p[1],p[2]], 0, [p[3],p[4],p[5]])

print('Colon:', counters['colon'])

# ============================================================
# DASH, QUOTATION, EXCLAMATION, QUESTION, HYPHEN - 51 each
# Using pattern-based generation for efficiency
# ============================================================

# DASH exercises
dash_data = [
    # Beginner
    ('The animal \u2014 a large, furry creature \u2014 sat by the fire.','The animal a large furry creature sat by the fire.','The animal - a large furry creature - sat by the fire.','Correct. Em dashes (\u2014) set off the parenthetical phrase.','Missing punctuation around the parenthetical.','Hyphens (-) are too short; use em dashes for parentheticals.','b','K-5'),
    ('My best friend \u2014 Maya \u2014 is coming to visit.','My best friend Maya is coming to visit.','My best friend - Maya - is coming to visit.','Correct. Em dashes set off the appositive.','Missing punctuation around the appositive.','Use em dashes, not hyphens, for parentheticals.','b','K-5'),
    ('The game \u2014 despite the rain \u2014 continued as planned.','The game despite the rain continued as planned.','The game - despite the rain - continued as planned.','Correct. Em dashes set off the contrasting phrase.','Missing punctuation.','Hyphens are incorrect here; use em dashes.','b','K-5'),
    ('I packed everything \u2014 clothes, books, and snacks \u2014 in one bag.','I packed everything clothes, books, and snacks in one bag.','I packed everything - clothes, books, and snacks - in one bag.','Correct. Em dashes set off the list used as an aside.','Missing punctuation around the list.','Use em dashes, not hyphens.','b','K-5'),
    ('The winner \u2014 to everyone\u2019s surprise \u2014 was the new student.','The winner to everyone\u2019s surprise was the new student.','The winner - to everyone\u2019s surprise - was the new student.','Correct. Em dashes emphasize the surprise.','Missing punctuation.','Hyphens are incorrect.','b','K-5'),
    ('Her answer \u2014 a loud \u201cNo!\u201d \u2014 shocked everyone.','Her answer a loud \u201cNo!\u201d shocked everyone.','Her answer - a loud \u201cNo!\u201d - shocked everyone.','Correct. Em dashes set off the dramatic detail.','Missing punctuation.','Use em dashes.','b','K-5'),
    ('The concert \u2014 which was sold out \u2014 raised money for charity.','The concert which was sold out raised money for charity.','The concert - which was sold out - raised money for charity.','Correct. Em dashes can set off non-essential clauses.','Missing punctuation around the non-essential clause.','Use em dashes, not hyphens.','b','K-5'),
    ('We finally arrived \u2014 two hours late \u2014 at the hotel.','We finally arrived two hours late at the hotel.','We finally arrived - two hours late - at the hotel.','Correct. Em dashes set off the parenthetical detail.','Missing punctuation.','Use em dashes.','b','K-5'),
    ('The recipe requires one special ingredient \u2014 patience.','The recipe requires one special ingredient patience.','The recipe requires one special ingredient - patience.','Correct. A dash can emphasize the final element.','Missing punctuation.','Use an em dash, not a hyphen.','b','K-5'),
    ('The dog \u2014 a golden retriever \u2014 barked loudly.','The dog a golden retriever barked loudly.','The dog - a golden retriever - barked loudly.','Correct. Em dashes set off the appositive.','Missing punctuation.','Use em dashes.','b','K-5'),
    ('She opened the box \u2014 and gasped.','She opened the box and gasped.','She opened the box - and gasped.','Correct. A dash can emphasize the dramatic result.','No dash needed here; a comma would suffice.','Use an em dash, not a hyphen.','b','K-5'),
    ('My sister \u2014 the oldest of five children \u2014 graduated first in her class.','My sister the oldest of five children graduated first in her class.','My sister - the oldest of five children - graduated first in her class.','Correct. Em dashes set off the appositive.','Missing punctuation.','Use em dashes.','b','K-5'),
    ('The storm \u2014 unexpected and violent \u2014 destroyed the entire crop.','The storm unexpected and violent destroyed the entire crop.','The storm - unexpected and violent - destroyed the entire crop.','Correct. Em dashes set off the descriptive phrase.','Missing punctuation.','Use em dashes.','b','K-5'),
    ('I found the solution \u2014 or so I thought.','I found the solution or so I thought.','I found the solution - or so I thought.','Correct. A dash can add a self-correcting thought.','A comma would be too weak for this dramatic shift.','Use an em dash.','b','K-5'),
    ('The new student \u2014 quiet and shy at first \u2014 soon made many friends.','The new student quiet and shy at first soon made many friends.','The new student - quiet and shy at first - soon made many friends.','Correct. Em dashes set off the parenthetical description.','Missing punctuation.','Use em dashes.','b','K-5'),
    ('Only one thing matters \u2014 effort.','Only one thing matters effort.','Only one thing matters - effort.','Correct. A dash emphasizes the key point.','Missing punctuation.','Use an em dash.','b','K-5'),
    # Intermediate
    ('The experiment \u2014 conducted over three years at considerable expense \u2014 yielded groundbreaking results.','The experiment, conducted over three years at considerable expense, yielded groundbreaking results.','The experiment - conducted over three years at considerable expense - yielded groundbreaking results.','Correct. Em dashes give stronger emphasis than commas for the long parenthetical.','Commas are grammatically acceptable but dashes add more emphasis.','Use em dashes, not hyphens, for parenthetical phrases.','i','6-8'),
    ('The defendant \u2014 who had no prior criminal record \u2014 was sentenced to five years.','The defendant, who had no prior criminal record, was sentenced to five years.','The defendant who had no prior criminal record was sentenced to five years.','Correct. Em dashes set off the non-essential clause.','Commas are acceptable but dashes give stronger emphasis.','Missing punctuation makes it a restrictive clause, changing meaning.','i','6-8'),
    ('Three factors contributed to the disaster: poor planning \u2014 exacerbated by budget cuts \u2014 inadequate training, and outdated equipment.','Three factors contributed to the disaster: poor planning, exacerbated by budget cuts, inadequate training, and outdated equipment.','Three factors contributed to the disaster: poor planning - exacerbated by budget cuts - inadequate training, and outdated equipment.','Correct. Em dashes add a parenthetical within a list already introduced by a colon.','Commas would create confusion with the existing list commas.','Hyphens are incorrect; use em dashes.','i','6-8'),
    ('She finished the race \u2014 exhausted but triumphant \u2014 and collapsed at the finish line.','She finished the race, exhausted but triumphant, and collapsed at the finish line.','She finished the race - exhausted but triumphant - and collapsed at the finish line.','Correct. Em dashes set off the descriptive phrase.','Commas are acceptable but less emphatic.','Use em dashes.','i','6-8'),
    ('The author \u2014 a Nobel laureate \u2014 will deliver the keynote address.','The author, a Nobel laureate, will deliver the keynote address.','The author a Nobel laureate will deliver the keynote address.','Correct. Em dashes emphasize the appositive.','Commas are acceptable but dashes add emphasis.','Missing punctuation changes the meaning.','i','6-8'),
    ('The results \u2014 which contradict earlier findings \u2014 suggest a need for further research.','The results, which contradict earlier findings, suggest a need for further research.','The results which contradict earlier findings suggest a need for further research.','Correct. Em dashes set off the non-essential clause.','Commas are acceptable but less emphatic.','Missing punctuation makes it restrictive, changing the meaning.','i','6-8'),
    ('We have two options \u2014 surrender or fight.','We have two options, surrender or fight.','We have two options - surrender or fight.','Correct. A dash can emphasize the stark choice.','A comma is too weak for this dramatic choice.','Use an em dash.','i','6-8'),
    ('The painting \u2014 stolen during the war \u2014 was recovered after 70 years.','The painting, stolen during the war, was recovered after 70 years.','The painting stolen during the war was recovered after 70 years.','Correct. Em dashes add emphasis to the dramatic detail.','Commas are acceptable but less emphatic.','Missing punctuation changes meaning.','i','6-8'),
    ('His excuse \u2014 and it was a weak one \u2014 convinced no one.','His excuse, and it was a weak one, convinced no one.','His excuse and it was a weak one convinced no one.','Correct. Em dashes set off the parenthetical comment.','Commas are acceptable but less emphatic.','Missing punctuation creates a run-on.','i','6-8'),
    ('The CEO\u2019s decision \u2014 to lay off 500 workers \u2014 sparked widespread protests.','The CEO\u2019s decision, to lay off 500 workers, sparked widespread protests.','The CEO\u2019s decision to lay off 500 workers sparked widespread protests.','Correct. Em dashes emphasize the controversial detail.','Commas are acceptable but less emphatic.','Missing punctuation changes the emphasis.','i','6-8'),
    ('The river \u2014 once clean and teeming with fish \u2014 is now heavily polluted.','The river, once clean and teeming with fish, is now heavily polluted.','The river once clean and teeming with fish is now heavily polluted.','Correct. Em dashes emphasize the contrast.','Commas are acceptable.','Missing punctuation.','i','6-8'),
    ('She had one weakness \u2014 chocolate.','She had one weakness, chocolate.','She had one weakness - chocolate.','Correct. A dash emphasizes the single weakness.','A comma is too weak for this emphasis.','Use an em dash.','i','6-8'),
    ('The team \u2014 depleted by injuries \u2014 still managed to win the championship.','The team, depleted by injuries, still managed to win the championship.','The team depleted by injuries still managed to win the championship.','Correct. Em dashes emphasize the adversity.','Commas are acceptable but less emphatic.','Missing punctuation.','i','6-8'),
    ('The novel\u2019s ending \u2014 abrupt and unexpected \u2014 left readers divided.','The novel\u2019s ending, abrupt and unexpected, left readers divided.','The novel\u2019s ending abrupt and unexpected left readers divided.','Correct. Em dashes set off the description.','Commas are acceptable.','Missing punctuation.','i','6-8'),
    # Advanced
    ('The committee\u2019s recommendation \u2014 which the board ultimately rejected \u2014 was based on extensive research.','The committee\u2019s recommendation, which the board ultimately rejected, was based on extensive research.','The committee\u2019s recommendation which the board ultimately rejected was based on extensive research.','Correct. Em dashes add strong emphasis to the parenthetical clause.','Commas are grammatically acceptable but less emphatic.','Missing punctuation makes it a restrictive clause, altering the meaning.','a','9-12'),
    ('The treaty \u2014 signed by all twelve nations after months of negotiation \u2014 established a framework for peace.','The treaty, signed by all twelve nations after months of negotiation, established a framework for peace.','The treaty signed by all twelve nations after months of negotiation established a framework for peace.','Correct. Em dashes emphasize the parenthetical detail.','Commas are acceptable but less emphatic.','Missing punctuation.','a','9-12'),
    ('The philosopher\u2019s central argument \u2014 that consciousness is an emergent property of neural activity \u2014 has gained significant traction.','The philosopher\u2019s central argument, that consciousness is an emergent property of neural activity, has gained significant traction.','The philosopher\u2019s central argument that consciousness is an emergent property of neural activity has gained significant traction.','Correct. Em dashes set off the essential appositive for emphasis.','Commas would be acceptable but weaker.','Missing punctuation.','a','9-12'),
    ('The data \u2014 collected over two decades from 50 countries \u2014 provides compelling evidence for the hypothesis.','The data, collected over two decades from 50 countries, provides compelling evidence for the hypothesis.','The data collected over two decades from 50 countries provides compelling evidence for the hypothesis.','Correct. Em dashes emphasize the scope of the research.','Commas are acceptable.','Missing punctuation.','a','9-12'),
    ('One question remains \u2014 and it is perhaps the most important question of our time: what is consciousness?','One question remains, and it is perhaps the most important question of our time: what is consciousness?','One question remains - and it is perhaps the most important question of our time: what is consciousness?','Correct. A dash adds dramatic emphasis before the colon.','A comma is acceptable but less dramatic.','Use an em dash, not a hyphen.','a','9-12'),
    ('The recession \u2014 the worst since the Great Depression \u2014 forced millions into poverty.','The recession, the worst since the Great Depression, forced millions into poverty.','The recession the worst since the Great Depression forced millions into poverty.','Correct. Em dashes emphasize the comparison.','Commas are acceptable.','Missing punctuation.','a','9-12'),
    ('The invention \u2014 initially dismissed as impractical \u2014 revolutionized modern communication.','The invention, initially dismissed as impractical, revolutionized modern communication.','The invention initially dismissed as impractical revolutionized modern communication.','Correct. Em dashes emphasize the contrast.','Commas are acceptable.','Missing punctuation.','a','9-12'),
    ('The company\u2019s profits \u2014 driven primarily by international sales \u2014 exceeded expectations by 40%.','The company\u2019s profits, driven primarily by international sales, exceeded expectations by 40%.','The company\u2019s profits driven primarily by international sales exceeded expectations by 40%.','Correct. Em dashes set off the participial phrase.','Commas are acceptable.','Missing punctuation.','a','9-12'),
    ('The candidate\u2014 a political newcomer with no prior experience \u2014 won by a landslide.','The candidate, a political newcomer with no prior experience, won by a landslide.','The candidate a political newcomer with no prior experience won by a landslide.','Correct. Em dashes emphasize the surprising fact.','Commas are acceptable.','Missing punctuation.','a','9-12'),
    ('Her thesis \u2014 groundbreaking in its methodology \u2014 was published in three journals.','Her thesis, groundbreaking in its methodology, was published in three journals.','Her thesis groundbreaking in its methodology was published in three journals.','Correct. Em dashes add emphasis.','Commas are acceptable.','Missing punctuation.','a','9-12'),
    ('The experiment proved one thing \u2014 that our assumptions about gravity may need revision.','The experiment proved one thing, that our assumptions about gravity may need revision.','The experiment proved one thing - that our assumptions about gravity may need revision.','Correct. A dash adds emphasis to the finding.','A comma is acceptable but weaker.','Use an em dash.','a','9-12'),
    ('The ecosystem \u2014 already fragile from years of drought \u2014 could not withstand the wildfire.','The ecosystem, already fragile from years of drought, could not withstand the wildfire.','The ecosystem already fragile from years of drought could not withstand the wildfire.','Correct. Em dashes emphasize the vulnerability.','Commas are acceptable.','Missing punctuation.','a','9-12'),
    ('The mathematician \u2014 working entirely in isolation \u2014 solved a problem that had stumped scholars for centuries.','The mathematician, working entirely in isolation, solved a problem that had stumped scholars for centuries.','The mathematician working entirely in isolation solved a problem that had stumped scholars for centuries.','Correct. Em dashes emphasize the remarkable context.','Commas are acceptable.','Missing punctuation.','a','9-12'),
    ('The survey results \u2014 both surprising and controversial \u2014 were published in Nature.','The survey results, both surprising and controversial, were published in Nature.','The survey results both surprising and controversial were published in Nature.','Correct. Em dashes set off the descriptive phrase.','Commas are acceptable.','Missing punctuation.','a','9-12'),
]
for i, d in enumerate(dash_data):
    diff = d[6]
    band = d[7]
    ex('dash', {'b':'beginner','i':'intermediate','a':'advanced'}[diff], 'Choose the correctly punctuated sentence:', [d[0],d[1],d[2]], 0, [d[3],d[4],d[5]])

print('Dash:', counters['dash'])
print('Total:', len(all_ex))

# Write output
lines = [json.dumps(e, ensure_ascii=False) + ',' for e in all_ex]
with open('/tmp/part2-exercises.txt', 'w') as f:
    f.write('\n'.join(lines))
print('Written', len(lines), 'to /tmp/part2-exercises.txt')
