import json

with open('/tmp/punct_final4.json') as f:
    exercises = json.load(f)

eid = max(int(e['id'].split('-')[-1]) for e in exercises)

def add(rule, diff, band, q, opts, ci, expls):
    global eid
    eid += 1
    exercises.append({'id': f'p-{rule}-{eid:03d}', 'rule': rule, 'difficulty': diff, 'band': band, 'question': q, 'options': opts, 'correctIndex': ci, 'explanations': expls})

final = [
('comma','intermediate','6-8','Choose the correctly punctuated sentence:','The recipe calls for sugar flour eggs and butter',['The recipe calls for sugar, flour, eggs and butter.','The recipe calls for sugar flour eggs and butter.','The recipe calls for sugar, flour, eggs, and butter.'],2,['Missing commas.','Missing Oxford comma.','Correct. All items separated with Oxford comma.']),
('comma','beginner','K-5','Choose the correctly punctuated sentence:','My mom dad and brother came to my game',['My mom, dad, and brother came to my game.','My mom dad and brother came to my game.','My mom, dad and brother came to my game.'],0,['Correct. Oxford comma separates list items.','Missing commas.','Missing Oxford comma.']),
('comma','intermediate','6-8','Choose the correctly punctuated sentence:','The test was hard but I passed',['The test was hard, but I passed.','The test was hard but I passed.','The test was hard; but I passed.'],0,['Correct. Comma before but.','Missing comma before but.','Semicolon before but is incorrect.']),
('comma','advanced','9-12','Choose the correctly punctuated sentence:','Not only did she win but she broke the record',['Not only did she win, but she broke the record.','Not only did she win but she broke the record.','Not only did she win; but she broke the record.'],0,['Correct. Comma before but.','Missing comma.','Semicolon before but is incorrect.']),
('comma','intermediate','6-8','Choose the correctly punctuated sentence:','The movie was long boring and predictable',['The movie was long, boring, and predictable.','The movie was long boring and predictable.','The movie was long, boring and predictable.'],0,['Correct. Commas separate coordinate adjectives.','Missing all commas.','Missing Oxford comma.']),
('comma','beginner','K-5','Choose the correctly punctuated sentence:','We bought apples oranges and bananas',['We bought apples, oranges, and bananas.','We bought apples oranges and bananas.','We bought apples, oranges and bananas.'],0,['Correct. Oxford comma.','Missing commas.','Missing Oxford comma.']),
('comma','advanced','9-12','Choose the correctly punctuated sentence:','The project which took three months was finally complete',['The project which took three months, was finally complete.','The project, which took three months, was finally complete.','The project which took three months was finally complete.'],1,['Only one comma; non-essential clauses need both.','Correct. Commas set off the non-essential clause.','Missing commas.']),
('comma','intermediate','6-8','Choose the correctly punctuated sentence:','In conclusion the evidence supports our hypothesis',['In conclusion the evidence supports our hypothesis.','In conclusion, the evidence supports our hypothesis.','In conclusion the evidence supports, our hypothesis.'],1,['Missing comma after the transitional phrase.','Correct. Comma after the transitional phrase.','Comma in the wrong position.']),
('colon','advanced','9-12','Choose the correctly punctuated sentence:','The study revealed one critical finding___the treatment reduced symptoms by 40 percent',['The study revealed one critical finding the treatment reduced symptoms by 40 percent.','The study revealed one critical finding: the treatment reduced symptoms by 40 percent.','The study revealed one critical finding, the treatment reduced symptoms by 40 percent.'],1,['Missing punctuation.','Correct. A colon introduces the finding.','Comma splice.']),
('colon','intermediate','6-8','Choose the correctly punctuated sentence:','She packed three things for the trip___snacks water and a map',['She packed three things for the trip snacks, water, and a map.','She packed three things for the trip: snacks, water, and a map.','She packed three things for the trip snacks water and a map.'],1,['Comma cannot introduce a list.','Correct. A colon introduces the list.','Missing all punctuation.']),
('colon','beginner','K-5','Choose the correctly punctuated sentence:','The schedule is as follows___8 AM breakfast 9 AM class',['The schedule is as follows: 8 AM breakfast, 9 AM class.','The schedule is as follows, 8 AM breakfast, 9 AM class.','The schedule is as follows 8 AM breakfast 9 AM class.'],0,['Correct. Colon follows as follows and commas separate items.','A comma is too weak.','Missing punctuation.']),
('colon','intermediate','6-8','Choose the correctly punctuated sentence:','He explained his reasoning___the evidence simply did not support it',['He explained his reasoning the evidence simply did not support it.','He explained his reasoning: the evidence simply did not support it.','He explained his reasoning, the evidence simply did not support it.'],1,['Missing punctuation.','Correct. A colon introduces the explanation.','Comma splice.']),
('colon','advanced','9-12','Choose the correctly punctuated sentence:','The philosopher made one essential distinction___knowledge and wisdom are fundamentally different',['The philosopher made one essential distinction knowledge and wisdom are fundamentally different.','The philosopher made one essential distinction: knowledge and wisdom are fundamentally different.','The philosopher made one essential distinction, knowledge and wisdom are fundamentally different.'],1,['Missing punctuation.','Correct. A colon introduces the emphasized distinction.','Comma splice.']),
('colon','beginner','K-5','Choose the correctly punctuated sentence:','I need one thing from you___your full attention',['I need one thing from you your full attention.','I need one thing from you: your full attention.','I need one thing from you, your full attention.'],1,['Missing punctuation.','Correct. A colon introduces the emphasized request.','Comma splice.']),
('colon','intermediate','6-8','Choose the correctly punctuated sentence:','Dear Mr Johnson___I hope this email finds you well',['Dear Mr Johnson: I hope this email finds you well.','Dear Mr Johnson, I hope this email finds you well.','Dear Mr Johnson I hope this email finds you well.'],0,['Correct. Colon after formal greeting.','A comma is too informal here.','Missing punctuation.']),
('dash','advanced','9-12','Choose the correctly punctuated sentence:','The implications of this discovery___which could reshape the field___are still being debated',['The implications of this discovery, which could reshape the field, are still being debated.','The implications of this discovery which could reshape the field are still being debated.','The implications of this discovery—which could reshape the field—are still being debated.'],2,['Commas work but dashes add more emphasis.','Missing punctuation.','Correct. Dashes emphasize the parenthetical.']),
('dash','intermediate','6-8','Choose the correctly punctuated sentence:','The new phone___which costs eight hundred dollars___has an amazing camera',['The new phone, which costs eight hundred dollars, has an amazing camera.','The new phone which costs eight hundred dollars has an amazing camera.','The new phone—which costs eight hundred dollars—has an amazing camera.'],2,['Missing punctuation.','Missing punctuation.','Correct. Dashes emphasize the parenthetical.']),
('dash','beginner','K-5','Choose the correctly punctuated sentence:','I found the answer___or so I thought',['I found the answer, or so I thought.','I found the answer or so I thought.','I found the answer—or so I thought.'],2,['Comma is too weak for self-correction.','Missing punctuation.','Correct. Dash adds emphasis to the self-correction.']),
('dash','advanced','9-12','Choose the correctly punctuated sentence:','She listed the benefits___cost savings improved morale and faster production___then presented the data',['She listed the benefits: cost savings, improved morale, and faster production—then presented the data.','She listed the benefits cost savings improved morale and faster production then presented the data.','She listed the benefits—cost savings, improved morale, and faster production—then presented the data.'],2,['Colon and commas are standard but less dramatic.','Missing punctuation.','Correct. Dashes add emphasis to the list.']),
('dash','intermediate','6-8','Choose the correctly punctuated sentence:','The concert___despite heavy rain___was incredible',['The concert, despite heavy rain, was incredible.','The concert despite heavy rain was incredible.','The concert—despite heavy rain—was incredible.'],2,['Standard but less emphatic.','Missing punctuation.','Correct. Dashes emphasize the contrast.']),
('quotation','advanced','9-12','Choose the correctly punctuated sentence:','The author states ___The only thing we have to fear is fear itself___ (Roosevelt)',['The author states "The only thing we have to fear is fear itself" (Roosevelt).','The author states The only thing we have to fear is fear itself (Roosevelt).','The author states "The only thing we have to fear is fear itself (Roosevelt)"'],0,['Correct. Quotes and citation properly formatted.','Missing quotation marks.','Citation should be outside.']),
('quotation','intermediate','6-8','Choose the correctly punctuated sentence:','She said ___I need to study___ and closed her book',['She said "I need to study" and closed her book.','She said I need to study and closed her book.','She said "I need to study and closed her book."'],0,['Correct. Quotes enclose the spoken words.','Missing quotation marks.','Too much inside the quotes.']),
('quotation','beginner','K-5','Choose the correctly punctuated sentence:','He told her ___Great job!___ with a smile',['He told her "Great job!" with a smile.','He told her Great job! with a smile.','He told her "Great job! with a smile."'],0,['Correct. Exclamation inside quotes.','Missing quotation marks.','Too much inside the quotes.']),
('quotation','intermediate','6-8','Choose the correctly punctuated sentence:','The first line of the poem is ___Two roads diverged in a yellow wood___',['The first line of the poem is "Two roads diverged in a yellow wood."','The first line of the poem is Two roads diverged in a yellow wood.','The first line of the poem is "Two roads diverged in a yellow wood"'],0,['Correct. Quoted text with proper punctuation.','Missing quotation marks.','Missing closing punctuation.']),
('quotation','advanced','9-12','Choose the correctly punctuated sentence:','She noted that ___language shapes thought___ in her analysis',['She noted that "language shapes thought" in her analysis.','She noted that language shapes thought in her analysis.','She noted that "language shapes thought in her analysis."'],0,['Correct. Quoted phrase in quotation marks.','Missing quotation marks.','Too much inside the quotes.']),
('quotation','intermediate','6-8','Choose the correctly punctuated sentence:','The sign said ___No Entry___ in red letters',['The sign said "No Entry" in red letters.','The sign said No Entry in red letters.','The sign said "No Entry in red letters."'],0,['Correct. Quotation marks around the sign text.','Missing quotation marks.','Too much inside the quotes.']),
('quotation','beginner','K-5','Choose the correctly punctuated sentence:','___Run!___ the coach yelled to the team',['"Run!" the coach yelled to the team.','Run! the coach yelled to the team.','"Run! the coach yelled to the team."'],0,['Correct. Quotation marks around the command.','Missing quotation marks.','Speaker tag should be outside.']),
('quotation','intermediate','6-8','Choose the correctly punctuated sentence:','He asked ___Can I borrow your pen___ politely',['He asked "Can I borrow your pen?" politely.','He asked Can I borrow your pen? politely.','He asked "Can I borrow your pen" politely.'],0,['Correct. Question mark inside quotes.','Missing quotation marks.','Too much inside the quotes.']),
('quotation','advanced','9-12','Choose the correctly punctuated sentence:','According to the report ___Innovation drives growth___ and we must invest accordingly',['According to the report, "Innovation drives growth" and we must invest accordingly.','According to the report "Innovation drives growth and we must invest accordingly."','According to the report, "Innovation drives growth" and we must invest accordingly.'],2,['Comma after report is correct; question mark inside quotes.','Too much inside the quotes.','Correct. Comma, quotes, and and.']),
('quotation','intermediate','6-8','Choose the correctly punctuated sentence:','Mom always says ___Early to bed early to rise___ to us',['Mom always says "Early to bed, early to rise" to us.','Mom always says Early to bed early to rise to us.','Mom always says "Early to bed early to rise" to us.'],0,['Correct. Quotation marks around the proverb.','Missing quotation marks.','Too much inside the quotes.']),
('quotation','beginner','K-5','Choose the correctly punctuated sentence:','The song ___Happy Birthday___ played during the party',['The song "Happy Birthday" played during the party.','The song Happy Birthday played during the party.','The song "Happy Birthday" played during the party."'],0,['Correct. Song titles in quotation marks.','Missing quotation marks.','Missing closing quotation mark.']),
('quotation','intermediate','6-8','Choose the correctly punctuated sentence:','She wrote in her journal ___Today was the best day of my life___',['She wrote in her journal "Today was the best day of my life."','She wrote in her journal Today was the best day of my life.','She wrote in her journal "Today was the best day of my life"'],0,['Correct. Quotation marks around the journal entry.','Missing quotation marks.','Missing closing punctuation.']),
('quotation','advanced','9-12','Choose the correctly punctuated sentence:','The professor emphasized ___Read the original text first___ before discussing interpretations',['The professor emphasized "Read the original text first" before discussing interpretations.','The professor emphasized Read the original text first before discussing interpretations.','The professor emphasized "Read the original text first before discussing interpretations."'],0,['Correct. Quotes around the instruction.','Missing quotation marks.','Too much inside the quotes.']),
('quotation','intermediate','6-8','Choose the correctly punctuated sentence:','The essay prompt asks ___What is the role of technology in education___',['The essay prompt asks "What is the role of technology in education?"','The essay prompt asks What is the role of technology in education?','The essay prompt asks "What is the role of technology in education?"'],0,['Correct. Quoted prompt with question mark inside quotes.','Missing quotation marks.','Question mark should be inside.']),
('quotation','beginner','K-5','Choose the correctly punctuated sentence:','He said ___I am so sorry___ with genuine regret',['He said "I am so sorry" with genuine regret.','He said I am so sorry with genuine regret.','He said "I am so sorry with genuine regret."'],0,['Correct. Quotation marks around the spoken words.','Missing quotation marks.','Too much inside the quotes.']),
('quotation','intermediate','6-8','Choose the correctly punctuated sentence:','The inscription on the trophy reads ___Most Valuable Player 2024___',['The inscription on the trophy reads "Most Valuable Player 2024."','The inscription on the trophy reads Most Valuable Player 2024.','The inscription on the trophy reads "Most Valuable Player 2024"'],0,['Correct. Inscription text in quotation marks.','Missing quotation marks.','Missing closing punctuation.']),
('quotation','advanced','9-12','Choose the correctly punctuated sentence:','She recalled him saying ___I never said I quit___ clearly',['She recalled him saying "I never said, I quit" clearly.','She recalled him saying "I never said I quit" clearly.','She recalled him saying I never said I quit clearly.'],0,['Correct. Nested quotes properly formatted.','Missing quotation marks.','Missing all quotation marks.']),
('quotation','intermediate','6-8','Choose the correctly punctuated sentence:','My teacher always says ___Practice makes perfect___',['My teacher always says "Practice makes perfect."','My teacher always says Practice makes perfect.','My teacher always says "Practice makes perfect"'],0,['Correct. Quotation marks around the proverb.','Missing quotation marks.','Missing closing punctuation.']),
]
for item in final:
    add(item[0],item[1],item[2],item[3],item[4],item[5],item[6])

print(f'GRAND TOTAL: {len(exercises)}')
from collections import Counter
c = Counter(e['rule'] for e in exercises)
for k,v in sorted(nc.items()): print(f'  {k}: {v}')
nc2 = Counter(e['difficulty'] for e in exercises)
for k,v in sorted(nc2.items()): print(f'  {k}: {v}')

with open('/tmp/punct_510.json', 'w') as f:
    json.dump(exercises, f)
print('FINAL!')
