import * as fs from 'fs'

const part1Lines = fs.readFileSync('/tmp/part1-exercises.txt', 'utf-8').trim().split('\n')

// Write the complete data file
let out = `// ============================================================
// Punctuation Exercises — 510+ exercises across 10 rules, 3 difficulties
// Auto-generated with hand-crafted educational content
// DO NOT edit this file manually — edit the generator scripts instead
// ============================================================

export type PunctRule =
  | 'period' | 'comma' | 'semicolon' | 'colon' | 'dash'
  | 'apostrophe' | 'quotation' | 'exclamation' | 'question' | 'hyphen'

export type Difficulty = 'beginner' | 'intermediate' | 'advanced'
export type GradeBand = 'K-5' | '6-8' | '9-12'

export interface PunctExercise {
  id: string
  rule: PunctRule
  difficulty: Difficulty
  band: GradeBand
  question: string
  options: [string, string, string]
  correctIndex: 0 | 1 | 2
  explanations: [string, string, string]
}

export const PUNCT_RULES: { id: PunctRule; label: string; description: string }[] = [
  { id: 'period', label: 'Period', description: 'End of sentences, abbreviations, initials' },
  { id: 'comma', label: 'Comma', description: 'Lists, introductory elements, compound sentences, appositives' },
  { id: 'semicolon', label: 'Semicolon', description: 'Joining independent clauses, complex lists' },
  { id: 'colon', label: 'Colon', description: 'Lists, explanations, formal greetings' },
  { id: 'dash', label: 'Dash', description: 'Parenthetical info, emphasis, interruptions' },
  { id: 'apostrophe', label: 'Apostrophe', description: 'Possessives, contractions, plurals of letters/numbers' },
  { id: 'quotation', label: 'Quotation Marks', description: 'Dialogue, titles, quotes within quotes' },
  { id: 'exclamation', label: 'Exclamation Mark', description: 'Commands, strong emotion, interjections' },
  { id: 'question', label: 'Question Mark', description: 'Direct questions, question vs statement' },
  { id: 'hyphen', label: 'Hyphen', description: 'Compound adjectives, compound numbers, prefixes' },
]

export const PUNCT_EXERCISES: PunctExercise[] = [
`

// Add part1 exercises
for (const line of part1Lines) {
  out += line + ',\n\n'
}

// Now write the semicolon, colon, dash, quotation, exclamation, question, hyphen exercises
// We'll read them from a separate file that we create next
const part2Path = '/tmp/part2-exercises.txt'
if (fs.existsSync(part2Path)) {
  const part2Lines = fs.readFileSync(part2Path, 'utf-8').trim().split('\n')
  for (const line of part2Lines) {
    if (line.trim()) out += line + ',\n\n'
  }
}

out += `]
`

fs.writeFileSync('src/data/punctuation-exercises.ts', out)
console.log('Written to src/data/punctuation-exercises.ts')
console.log('Part1 exercises:', part1Lines.length)
